### ISSUE TITLE
npm start 后产生error

### ISSUE THREAD

**Issue by thomastao0215** [dvajs/dva-gui#26]
jiachen215 (master #) dva-gui-master $ npm start

> @ start /Users/jiachen215/Documents/lmtry/tools/dva-gui-master
> electron app/dist/main

App threw an error during load
Error: Cannot find module 'electron-is'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/jiachen215/Documents/lmtry/tools/dva-gui-master/node_modules/.1.4.13@electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jiachen215/Documents/lmtry/tools/dva-gui-master/app/dist/main.js:146:19)
    at __webpack_require__ (/Users/jiachen215/Documents/lmtry/tools/dva-gui-master/app/dist/main.js:20:30)
    at Object.<anonymous> (/Users/jiachen215/Documents/lmtry/tools/dva-gui-master/app/dist/main.js:51:20)
    at __webpack_require__ (/Users/jiachen215/Documents/lmtry/tools/dva-gui-master/app/dist/main.js:20:30)
    at /Users/jiachen215/Documents/lmtry/tools/dva-gui-master/app/dist/main.js:40:18

----------------------------------------------------------------------------------------------------
jiachen215 (master #) dva-gui-master $ npm run dev

> @ dev /Users/jiachen215/Documents/lmtry/tools/dva-gui-master
> webpack -w

Live Reload listening on port 35729

Hash: 6f8bf0049fb6209f33c1
Version: webpack 1.14.0
Time: 9193ms
  Asset     Size  Chunks             Chunk Names
main.js  12.5 kB       0  [emitted]  main
    + 16 hidden modules
Hash: 377cb4af0bc434027fd3
Version: webpack 1.14.0
Time: 43976ms
          Asset     Size  Chunks             Chunk Names
    renderer.js   3.4 MB       0  [emitted]  renderer
renderer.js.map  4.08 MB       0  [emitted]  renderer
    + 894 hidden modules

**Comment by sorrycc** [comment]
还在开发中，先别用。

**Comment by thomastao0215** [comment]
好 谢谢

2017-01-04 13:42 GMT+08:00 chencheng (云谦) <notifications@github.com>:
